ALTER TYPE "PetTransportStatus" ADD VALUE IF NOT EXISTS 'AWAITING_PAYMENT';
ALTER TYPE "PetTransportStatus" ADD VALUE IF NOT EXISTS 'ON_HOLD';
ALTER TYPE "PetTransportStatus" ADD VALUE IF NOT EXISTS 'READY_FOR_TRANSPORT';
ALTER TYPE "PetTransportStatus" ADD VALUE IF NOT EXISTS 'OUT_FOR_DELIVERY';
