#!/usr/bin/env bash
set -Eeuo pipefail

OUTPUT_FILE="${1:-/etc/nginx/conf.d/cloudflare-real-ip.conf}"
TMP_FILE="$(mktemp)"

{
  echo "# Generated by deploy/scripts/update-cloudflare-ips.sh"
  echo "# Refresh this file periodically because Cloudflare IP ranges can change."
  curl -fsSL https://www.cloudflare.com/ips-v4 | while read -r ip; do
    echo "set_real_ip_from $ip;"
  done
  curl -fsSL https://www.cloudflare.com/ips-v6 | while read -r ip; do
    echo "set_real_ip_from $ip;"
  done
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "$TMP_FILE"

sudo install -m 0644 "$TMP_FILE" "$OUTPUT_FILE"
rm -f "$TMP_FILE"

sudo nginx -t
sudo systemctl reload nginx

echo "Cloudflare real IP configuration updated at $OUTPUT_FILE"
